#!/bin/bash
echo "Haciendo una copia de la base de datos...";
./dbdump;
#exit;
echo "";
echo "Añadiendo los cambios locales...";
git add .;
git commit -m "$1";
echo "";
echo "Descargando los ultimos cambios...";
git pull origin master;
echo "";
echo "Subiendo los ultimos cambios...";
git push origin master;

echo "Cambios subidos con exito";
echo "";
exit;